import CryptoKit
import Foundation

/// Pairing material generated by Warden. No SSH or provider authentication secrets are used.
public struct RemoteFeed: Codable, Equatable {
    public var relay: String
    public var room: String
    public var readerToken: String
    public var publisherToken: String
    public var key: String

    public init(relay: String) {
        self.relay = relay
        room = RemotePhoneCrypto.token(); readerToken = RemotePhoneCrypto.token()
        publisherToken = RemotePhoneCrypto.token(); key = RemotePhoneCrypto.token()
    }

    public static func url(_ value: String, allowLocalHTTP: Bool = false) -> URL? {
        guard let url = URL(string: value), url.host != nil, url.user == nil, url.password == nil,
              url.query == nil, url.fragment == nil, url.path.isEmpty || url.path == "/" else { return nil }
        if url.scheme == "https" { return url }
        if allowLocalHTTP, url.scheme == "http", ["127.0.0.1", "localhost"].contains(url.host ?? "") { return url }
        return nil
    }

    public var valid: Bool {
        [room, readerToken, publisherToken, key].allSatisfy { RemotePhoneCrypto.decode($0)?.count == 32 }
    }

    public func open(_ packet: String) throws -> Data {
        guard packet.utf8.count <= 3_000_000, let bytes = RemotePhoneCrypto.decode(packet),
              let secret = RemotePhoneCrypto.decode(key), secret.count == 32 else { throw RemotePhoneCrypto.Failure.invalidPacket }
        let derived = HKDF<SHA256>.deriveKey(inputKeyMaterial: SymmetricKey(data: secret), salt: Data(room.utf8),
                                            info: Data("warden.feed.toMac.v1".utf8), outputByteCount: 32)
        return try AES.GCM.open(AES.GCM.SealedBox(combined: bytes), using: derived)
    }
}

/// A fresh connection challenge and increasing counter keep replayed ciphertext from extending liveness.
public struct RemoteFeedEnvelope: Decodable {
    public var challenge: String
    public var sequence: Int
    public var snapshot: RemoteSnapshot
}
